<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pseudocodi</string>
	</array>
	<key>name</key>
	<string>Pseudocodi</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comentaris</string>
			<key>match</key>
			<string>(?&lt;!=\s)((\{).*(\}))</string>
			<key>name</key>
			<string>comment.line.note.pseudocode</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Paraules clau de control</string>
			<key>match</key>
			<string>\b(per|fper|mentre|fmentre|si|fsi|llavors|sino|fins|fer|pas)\b</string>
			<key>name</key>
			<string>keyword.control.pseudocode</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Altres paraules clau</string>
			<key>match</key>
			<string>\b(const|fconst|tipus|ftipus|var|fvar|de|retorna|punter a)\b</string>
			<key>name</key>
			<string>keyword.other.pseudocode</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Tipus modificadors</string>
			<key>match</key>
			<string>\b(ent|sor|entsor)\b</string>
			<key>name</key>
			<string>storage.modifier.pseudocode</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Tipus predefinits</string>
			<key>match</key>
			<string>\b(enter|real|caracter|boolea|taula|tupla|ftupla)\b</string>
			<key>name</key>
			<string>storage.type.pseudocode</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.pseudocodi</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Accés als elements d'una tupla</string>
			<key>match</key>
			<string>(\.)([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>entity.other.attribute-name</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constants numériques</string>
			<key>match</key>
			<string>-?\b\d+(.\d+E?\d)?\b</string>
			<key>name</key>
			<string>constant.numeric.pseudocode</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constants predefinides</string>
			<key>match</key>
			<string>\b(ENTERMAX|ENTERMIN|REALMAX|REALMIN)\b</string>
			<key>name</key>
			<string>constant.other.pseudocode</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constants del llenguatges</string>
			<key>match</key>
			<string>\b(cert|fals|NUL)\b</string>
			<key>name</key>
			<string>constant.language.pseudocode</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operador i</string>
			<key>match</key>
			<string>\b(i)\b(?=\s[\w\d]+)</string>
			<key>name</key>
			<string>keyword.operator.pseudocodi</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Altres operadors alfanumérics</string>
			<key>match</key>
			<string>\b(o|no|div|mod)\b</string>
			<key>name</key>
			<string>keyword.operator.pseudocodi</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Altres operadors simbols</string>
			<key>match</key>
			<string>=|=/|:=|&lt;|&lt;=|&gt;|&gt;=|\*|/|\+|-|:|;|≤|\.|^|,</string>
			<key>name</key>
			<string>keyword.operator.pseudocodi</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.pseudocode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Funcions</string>
			<key>match</key>
			<string>(\bfuncio\b(\s[A-Za-z_][A-Za-z0-9_]*)(?=\(.*\)\s*:\s*.+))|\bffuncio\b</string>
			<key>name</key>
			<string>storage.type.function.pseudocode</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.pseudocodi</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Crida a accions i funcions predefinides</string>
			<key>match</key>
			<string>\b(realAEnter|enterAReal|caracterACodi|codiACaracter|llegirEnter|llegirReal|llegirCaracter|escriureEnter|escriureReal|escriureCaracter|)\b(?=\(.*\))</string>
			<key>name</key>
			<string>support.function.pseudocodi</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Crida a funcions i accions</string>
			<key>match</key>
			<string>([A-Za-z_][A-Za-z0-9_]*)(?=\(.*\))</string>
			<key>name</key>
			<string>storage.type.function.pseudocode</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.pseudocode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Accions</string>
			<key>match</key>
			<string>(\baccio\b(\s[A-Za-z_][A-Za-z0-9_]*)(?=\(.*\)))|\bfaccio\b</string>
			<key>name</key>
			<string>storage.type.function.pseudocode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pseudocode</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Cometes simples</string>
			<key>end</key>
			<string>(')</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pseudocode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.pseudocode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.pseudocode</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Cometes dobles</string>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.pseudocode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.pseudocode</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\b(algorisme)\b\s([A-Za-z][A-Za-z0-0_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.algorisme.pseudocode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Ambit del algorisme</string>
			<key>end</key>
			<string>(falgorisme)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.algorisme.pseudocode</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.algorisme.pseudocode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=[A-Za-z_][A-Za-z0-9_]*)</string>
					<key>contentName</key>
					<string>entity.name.function.pseudocode</string>
					<key>end</key>
					<string>(?![A-Za-z0-9_])</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pseudocodi</string>
	<key>uuid</key>
	<string>0da65be4-5aac-4b6f-8071-1aadb970b8d9</string>
</dict>
</plist>
